### ISSUE TITLE
.

### ISSUE THREAD

**Issue by View-my-Git-Lab-krafi** [LegionGames/Conductor-Example#1]
.

**Comment by View-my-Git-Lab-krafi** [comment]
https://github.com/EndersteveGamer/Friday-night-funkin-with-Pygame/issues/14

[`https://github.com/EndersteveGamer/Friday-night-funkin-with-Pygame/issues/14`](https://github.com/EndersteveGamer/Friday-night-funkin-with-Pygame/issues/14)

**Comment by krafi-code** [comment]
I'm sorry, I accidentally created this file here.
